Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'C:\Users\juanm\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip' command.


In [532]:
import pandas as pd
import numpy as np

In [533]:
df = pd.read_csv('G:/ProjectoScikit/Leads.csv')
print(len(df))
df.head().T

9240


0  \
Prospect ID                                    7927b2df-8bba-4d29-b9a2-b6e0beafe620   
Lead Number                                                                  660737   
Lead Origin                                                                     API   
Lead Source                                                              Olark Chat   
Do Not Email                                                                     No   
Do Not Call                                                                      No   
Converted                                                                         0   
TotalVisits                                                                     0.0   
Total Time Spent on Website                                                       0   
Page Views Per Visit                                                            0.0   
Last Activity                                               Page Visited on Website   
Country                                                                         NaN   
Specialization                                                               Select   
How did you hear about X Education                                           Select   
What is your current occupation                                          Unemployed   
What matters most to you in choosing a course               Better Career Prospects   
Search                                                                           No   
Magazine                                                                         No   
Newspaper Article                                                                No   
X Education Forums                                                               No   
Newspaper                                                                        No   
Digital Advertisement                                                            No   
Through Recommendations                                                          No   
Receive More Updates About Our Courses                                           No   
Tags                                                    Interested in other courses   
Lead Quality                                                       Low in Relevance   
Update me on Supply Chain Content                                                No   
Get updates on DM Content                                                        No   
Lead Profile                                                                 Select   
City                                                                         Select   
Asymmetrique Activity Index                                               02.Medium   
Asymmetrique Profile Index                                                02.Medium   
Asymmetrique Activity Score                                                    15.0   
Asymmetrique Profile Score                                                     15.0   
I agree to pay the amount through cheque                                         No   
A free copy of Mastering The Interview                                           No   
Last Notable Activity                                                      Modified   

                                                                                  1  \
Prospect ID                                    2a272436-5132-4136-86fa-dcc88c88f482   
Lead Number                                                                  660728   
Lead Origin                                                                     API   
Lead Source                                                          Organic Search   
Do Not Email                                                                     No   
Do Not Call                                                                      No   
Converted                                                                         0   
TotalVisits                                                                    

In [534]:
df.dtypes

Prospect ID                                       object
Lead Number                                        int64
Lead Origin                                       object
Lead Source                                       object
Do Not Email                                      object
Do Not Call                                       object
Converted                                          int64
TotalVisits                                      float64
Total Time Spent on Website                        int64
Page Views Per Visit                             float64
Last Activity                                     object
Country                                           object
Specialization                                    object
How did you hear about X Education                object
What is your current occupation                   object
What matters most to you in choosing a course     object
Search                                            object
Magazine                       

In [535]:
replacer = lambda str: str.lower().str.replace(' ', '_')
df.columns = replacer(df.columns.str)
for col in list(df.dtypes[df.dtypes == 'object'].index):
    df[col] = replacer(df[col].str)
df.head().T

0  \
prospect_id                                    7927b2df-8bba-4d29-b9a2-b6e0beafe620   
lead_number                                                                  660737   
lead_origin                                                                     api   
lead_source                                                              olark_chat   
do_not_email                                                                     no   
do_not_call                                                                      no   
converted                                                                         0   
totalvisits                                                                     0.0   
total_time_spent_on_website                                                       0   
page_views_per_visit                                                            0.0   
last_activity                                               page_visited_on_website   
country                                                                         NaN   
specialization                                                               select   
how_did_you_hear_about_x_education                                           select   
what_is_your_current_occupation                                          unemployed   
what_matters_most_to_you_in_choosing_a_course               better_career_prospects   
search                                                                           no   
magazine                                                                         no   
newspaper_article                                                                no   
x_education_forums                                                               no   
newspaper                                                                        no   
digital_advertisement                                                            no   
through_recommendations                                                          no   
receive_more_updates_about_our_courses                                           no   
tags                                                    interested_in_other_courses   
lead_quality                                                       low_in_relevance   
update_me_on_supply_chain_content                                                no   
get_updates_on_dm_content                                                        no   
lead_profile                                                                 select   
city                                                                         select   
asymmetrique_activity_index                                               02.medium   
asymmetrique_profile_index                                                02.medium   
asymmetrique_activity_score                                                    15.0   
asymmetrique_profile_score                                                     15.0   
i_agree_to_pay_the_amount_through_cheque                                         no   
a_free_copy_of_mastering_the_interview                                           no   
last_notable_activity                                                      modified   

                                                                                  1  \
prospect_id                                    2a272436-5132-4136-86fa-dcc88c88f482   
lead_number                                                                  660728   
lead_origin                                                                     api   
lead_source                                                          organic_search   
do_not_email                                                                     no   
do_not_call                                                                      no   
converted                                                                         0   
totalvisits                                                                    

In [536]:
df.isnull().sum()

prospect_id                                         0
lead_number                                         0
lead_origin                                         0
lead_source                                        36
do_not_email                                        0
do_not_call                                         0
converted                                           0
totalvisits                                       137
total_time_spent_on_website                         0
page_views_per_visit                              137
last_activity                                     103
country                                          2461
specialization                                   1438
how_did_you_hear_about_x_education               2207
what_is_your_current_occupation                  2690
what_matters_most_to_you_in_choosing_a_course    2709
search                                              0
magazine                                            0
newspaper_article           

In [537]:
df.isnull().any(axis=1).sum()

7297

In [538]:
df["lead_source"].value_counts()
df["totalvisits"].value_counts()
df["page_views_per_visit"].value_counts()
df["last_activity"].value_counts()
df["country"].value_counts()
df["specialization"].value_counts()
df["how_did_you_hear_about_x_education"].value_counts()
df["what_is_your_current_occupation"].value_counts()
df["what_matters_most_to_you_in_choosing_a_course"].value_counts()
df["tags"].value_counts()
df["lead_quality"].value_counts()
df["lead_profile"].value_counts()
df["city"].value_counts()
df["asymmetrique_activity_index"].value_counts()
df["asymmetrique_profile_index"].value_counts()
df["asymmetrique_activity_score"].value_counts()
df["asymmetrique_profile_score"].value_counts()


15.0    1759
18.0    1071
16.0     599
17.0     579
20.0     308
19.0     245
14.0     226
13.0     204
12.0      22
11.0       9
Name: asymmetrique_profile_score, dtype: int64

In [539]:
df.tags = df.tags.fillna("unknown")
df.lead_source = df.lead_source.fillna("unknown")
df.city = df.city.fillna("other_cities")
df.lead_source = df.lead_source.fillna("unknown")
df.totalvisits = df.totalvisits.fillna(np.nanmedian(df.totalvisits))
df.page_views_per_visit = df.page_views_per_visit.fillna(0)
df.last_activity = df.last_activity.fillna("unknown")
df.specialization = df.specialization.fillna("unknown")
df.what_is_your_current_occupation = df.what_is_your_current_occupation.fillna("unemployed")

In [540]:
df = df.drop(columns='prospect_id')
df = df.drop(columns='lead_number')
df = df.drop(columns='lead_quality')
df = df.drop(columns='lead_profile')
df = df.drop(columns='a_free_copy_of_mastering_the_interview')
df = df.drop(columns='through_recommendations')
df = df.drop(columns='digital_advertisement')
df = df.drop(columns='newspaper_article')
df = df.drop(columns='do_not_call')
df = df.drop(columns='newspaper')
df = df.drop(columns='what_matters_most_to_you_in_choosing_a_course')
df = df.drop(columns='search')
df = df.drop(columns='how_did_you_hear_about_x_education')
df = df.drop(columns='x_education_forums')
df = df.drop(columns='magazine')
df = df.drop(columns='receive_more_updates_about_our_courses')
df = df.drop(columns='update_me_on_supply_chain_content')
df = df.drop(columns='get_updates_on_dm_content')
df = df.drop(columns='i_agree_to_pay_the_amount_through_cheque')
df = df.drop(columns='asymmetrique_activity_index')
df = df.drop(columns='asymmetrique_profile_index')
df = df.drop(columns='asymmetrique_activity_score')
df = df.drop(columns='asymmetrique_profile_score')
df = df.drop(columns='country')


In [541]:
categorical = ['lead_origin','lead_source','do_not_email','last_activity','specialization','what_is_your_current_occupation','city','last_notable_activity','tags']

numerical = ['totalvisits','total_time_spent_on_website','page_views_per_visit']

df[categorical].nunique()

lead_origin                         5
lead_source                        21
do_not_email                        2
last_activity                      18
specialization                     20
what_is_your_current_occupation     6
city                                7
last_notable_activity              16
tags                               27
dtype: int64

In [542]:
from sklearn.model_selection import train_test_split
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=1)

df_train, df_val = train_test_split(df_train_full, test_size=0.33, random_state=1)
y_train = df_train.converted.values
y_val = df_val.converted.values

del df_train['converted']
del df_val['converted']

In [543]:
global_mean = df_train_full.converted.mean()
round(global_mean, 3)

0.383

In [544]:
from sklearn.metrics import mutual_info_score

calculate_mi = lambda col: mutual_info_score(col, df_train_full.converted)

df_mi = df_train_full[categorical].apply(calculate_mi)
df_mi = df_mi.sort_values(ascending=False).to_frame(name='MI')
df_mi

MI
tags                             0.376991
last_activity                    0.088539
last_notable_activity            0.072517
lead_source                      0.062451
lead_origin                      0.055599
what_is_your_current_occupation  0.053127
specialization                   0.037845
city                             0.022967
do_not_email                     0.008911

In [545]:
train_dict = df_train[categorical + numerical].to_dict(orient='records')
dict(sorted(train_dict[0].items()))

{'city': 'other_cities_of_maharashtra',
 'do_not_email': 'no',
 'last_activity': 'converted_to_lead',
 'last_notable_activity': 'modified',
 'lead_origin': 'landing_page_submission',
 'lead_source': 'direct_traffic',
 'page_views_per_visit': 3.0,
 'specialization': 'marketing_management',
 'tags': 'ringing',
 'total_time_spent_on_website': 1625,
 'totalvisits': 3.0,
 'what_is_your_current_occupation': 'unemployed'}

In [546]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [547]:
X_train = dv.transform(train_dict)
X_train[0]

array([0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 3.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 

In [548]:
dv.get_feature_names_out()

array(['city=mumbai', 'city=other_cities',
       'city=other_cities_of_maharashtra', 'city=other_metro_cities',
       'city=select', 'city=thane_&_outskirts', 'city=tier_ii_cities',
       'do_not_email=no', 'do_not_email=yes',
       'last_activity=approached_upfront',
       'last_activity=converted_to_lead', 'last_activity=email_bounced',
       'last_activity=email_link_clicked',
       'last_activity=email_marked_spam', 'last_activity=email_opened',
       'last_activity=email_received',
       'last_activity=form_submitted_on_website',
       'last_activity=had_a_phone_conversation',
       'last_activity=olark_chat_conversation',
       'last_activity=page_visited_on_website',
       'last_activity=resubscribed_to_emails', 'last_activity=sms_sent',
       'last_activity=unknown', 'last_activity=unreachable',
       'last_activity=unsubscribed',
       'last_activity=view_in_browser_link_clicked',
       'last_notable_activity=email_bounced',
       'last_notable_activity=email

In [549]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear')
model.fit(X_train, y_train)

LogisticRegression(solver='liblinear')

In [550]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)
y_pred = model.predict_proba(X_val)
y_pred

array([[0.9741275 , 0.0258725 ],
       [0.02768291, 0.97231709],
       [0.89694539, 0.10305461],
       ...,
       [0.98523773, 0.01476227],
       [0.90463646, 0.09536354],
       [0.76904296, 0.23095704]])

In [551]:
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([0.0258725 , 0.97231709, 0.10305461, ..., 0.01476227, 0.09536354,
       0.23095704])

In [552]:
churn = y_pred >= 0.5
churn

array([False,  True, False, ..., False, False, False])

In [553]:
round((y_val == churn).mean(), 3) 

0.932

In [ ]:
pip install flask

In [558]:
import pickle

In [559]:
with open('G:/ProjectoScikit/modelos/converted-model.pck', 'wb') as f:
    pickle.dump((dv, model), f)

In [561]:
with open('G:/ProjectoScikit/modelos/converted-model.pck', 'rb') as f:
    dv, model = pickle.load(f)
    X_val = dv.transform(val_dict)
    y_pred = model.predict_proba(X_val)

y_pred

array([[0.9741275 , 0.0258725 ],
       [0.02768291, 0.97231709],
       [0.89694539, 0.10305461],
       ...,
       [0.98523773, 0.01476227],
       [0.90463646, 0.09536354],
       [0.76904296, 0.23095704]])